spring:
                  datasource:
                    url: jdbc:mysql://localhost:3306/springbootdb?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&autoReconnect=true&failOverReadOnly=false
                    username: root
                    password: wujinxing718
                    driver-class-name: com.mysql.cj.jdbc.Driver
                  jpa:
                    database: mysql
                    show-sql: true
                    hibernate:
                      ddl-auto: update